/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  developerDocumentation: [
    {
      type: "autogenerated",
      dirName: "developer-documentation",
    },
  ],
  tutorial: [
    {
      type: "autogenerated",
      dirName: "tutorial",
    },
  ],
  designSystem: [
    {
      type: "autogenerated",
      dirName: "design-system",
    },
  ],
  about: [
    {
      type: "autogenerated",
      dirName: "about",
    },
  ],
};

export default sidebars;
